### In this hands-on you will be performing CNN operations using TensorFlow package

- Run the below cell to import necessary packages

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
import tensorflow as tf

- Read the image file 'bird.jpeg'(in current directory) using **mpimg.imread("file_path")** function provided by matplotlib.image module. This function reads the image and returns the pixel intensities in numpy format. Assign this result to variable **img**.
- The dimension of **img** will now be $n_H$ x $n_w$ x $n_c$
- reshape **img** to dimension $m$ x $n_H$ x $n_w$ x $n_c$ and assign it to variable **data**. The dimension **m** will be **one** since we are dealing with one image data. (use numpy's reshape())

In [ ]:
img = mpimg.imread('bird.jpeg')
print(type(img))
print("Image dimension ",img.shape)
print(img.shape)
data = img[:,:,:].reshape(1,194,259,3)
print("input data dimension ", data.shape)

- Run the below cell to plot the image

In [ ]:
plt.imshow(data[0,:,:,:])

### Single layer convolution
- Initialise filter variable W each with random values using tf.random_normal()
  - filter configurations:
    - num_filters = 32
    - num_rows, num_columns, num_channels = 5,5,3 
- initilze bias variable using tf.random_normal() of shape 32

- using tf.nn.conv2d() perform strided convolution on **input_** using filter **W** of stride one and same padding, assign the result to variable **conv**
- use tf.nn.bias_add() to add biase **b** to vector **conv** and assign the result to variable **conv_bias**
- apply relu activation on vector **conv_bias** and assign it to variable **conv_out**
- perform max pooling using tf.nn.pool() using filter of size 3 x 3 and valid padding

In [ ]:
graph = tf.Graph()   
with graph.as_default():
    tf.set_random_seed(1)
    input_= tf.constant(data.astype(np.float32))  ##The input data is coverted into tensor of type float32
    ###Start code here
    W = 
    b = 
    
     
    conv = 
    conv_bias = 
    conv_out = 
    conv_pool = 
    ###ENd code

- Run the below cell to run the tensorflow graph defined in the above steps

Expected output  
Tensor("Relu:0", shape=(1, 194, 259, 32), dtype=float32)

Tensor("max_pool:0", shape=(1, 192, 257, 32), dtype=float32)  

[[169.19849 239.264   243.78383 199.24991 221.47708]  
 [257.10614 264.71    329.7318  268.09598 202.37561]  
 [270.35233 263.85138 300.23892 201.36992 156.39926]  
 [147.51581 180.1401  219.85764 224.4273  239.723  ]  
 [119.10833 209.67384 216.4677  276.01907 353.46246]]  
  
 [[329.7318  329.7318  329.7318  273.27444 316.57968]  
 [329.7318  329.7318  329.7318  273.27444 316.57968]  
 [300.23892 300.23892 353.46246 353.46246 353.46246]  
 [292.92957 292.92957 359.3247  359.3247  381.27603]  
 [315.04044 292.92957 405.957   418.59485 418.59485]]  

In [ ]:
with tf.Session(graph=graph) as sess:
    sess.run(tf.global_variables_initializer())
    filters = sess.run(W)
    
    conv_output = sess.run(conv_out)
    
    after_pooling = sess.run(conv_pool)

###sanity check
print(conv_out)
print(conv_pool)
print(conv_output[0,100:105,200:205, 7])
print("\n", after_pooling[0,100:105,200:205, 7])

print(np.mean(conv_output))
print(np.mean(after_pooling))
with open("output.txt", "w+") as file:
    file.write("mean1 = %f" %np.mean(conv_output))
    file.write("\nmean2 = %f" %np.mean(after_pooling))

- Run the below cell to visualize the actual filters and plot the convolution output.       

In [ ]:
def show_conv_results(data, title):
    fig1 = plt.figure()
    fig1.suptitle(title, fontsize=30)
    rows, cols = 4, 8
    for i in range(np.shape(data)[3]):
        img = data[0, :, :, i]
        ax1 = fig1.add_subplot(rows, cols, i + 1)
        ax1.imshow(img, interpolation='none')
        ax1.axis('off')
        

def show_weights(W,title):
    fig2 = plt.figure()
    fig2.suptitle(title, fontsize=30)
    rows, cols = 4, 8
    for i in range(np.shape(W)[3]):
        img = W[:, :, 0, i]
        ax2 = fig2.add_subplot(rows, cols, i + 1)
        ax2.imshow(img, interpolation='none')
        ax2.axis('off')

show_weights(filters, title = "filters, "+"shape:" +str(filters.shape))
show_conv_results(conv_output, title = "after_convolution, "+ "shape:" + str(conv_output.shape))
show_conv_results(after_pooling, title = "after_pooling, "+"shape:"+str(after_pooling.shape))
        