### In this hands-on you will be performing CNN operations using TensorFlow package

- Run the below cell to import necessary packages

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
import tensorflow as tf

- Read the image file 'bird.jpeg'(in current directory) using **mpimg.imread("file_path")** function provided by matplotlib.image module. This function reads the image and returns the pixel intensities in numpy format. Assign this result to variable **img**.
- The dimension of **img** will now be $n_H$ x $n_w$ x $n_c$
- reshape **img** to dimension $m$ x $n_H$ x $n_w$ x $n_c$ and assign it to variable **data**. The dimension **m** will be **one** since we are dealing with one image data. (use numpy's reshape())

In [ ]:
###Start code here
img = 
data = 
###End code

print(type(img))
print("Image dimension ",img.shape)
print(img.shape)
print("input data dimension ", data.shape)

- Run the below cell to plot the image

In [ ]:
plt.imshow(data[0,:,:,:])

### Single layer convolution
- Initialise filter variable W each with random values using tf.random_normal()
  - filter configurations:
    - num_filters = 32
    - num_rows, num_columns, num_channels = 5,5,3 
- initilze bias variable using tf.random_normal() of shape 32

- using tf.nn.conv2d() perform strided convolution on **input_** using filter **W** of stride one and same padding, assign the result to variable **conv**
- use tf.nn.bias_add() to add biase **b** to vector **conv** and assign the result to variable **conv_bias**
- apply relu activation on vector **conv_bias** and assign it to variable **conv_out**
- perform max pooling using tf.nn.pool() using filter of size 3 x 3 and valid padding

In [ ]:
graph = tf.Graph()   
with graph.as_default():
    tf.set_random_seed(1)
    input_= tf.constant(data.astype(np.float32))  ##The input data is coverted into tensor of type float32
    ###Start code here
    W = 
    b = 
    
     
    conv = 
    conv_bias = 
    conv_out = 
    conv_pool = 
    ###ENd code

- Run the below cell to run the tensorflow graph defined in the above steps

Expected output  
Tensor("Relu:0", shape=(1, 194, 259, 32), dtype=float32)

Tensor("max_pool:0", shape=(1, 192, 257, 32), dtype=float32)  

[[145.88837 215.9097  263.08267 323.85458 330.825  ]  
 [102.77487 171.201   235.99557 286.4785  349.71017]  
 [280.6651  288.21014 304.72537 231.75516 239.08713]  
 [399.53613 341.55472 285.87732 270.19873 264.35022]  
 [322.49316 312.23904 301.545   334.06796 344.6541 ]]  

 [[304.72537 323.85458 349.71017 349.71017 349.71017]  
 [399.53613 341.55472 349.71017 349.71017 349.71017]  
 [399.53613 341.55472 344.6541  344.6541  344.6541 ]  
 [399.53613 341.55472 355.1909  461.62012 461.62012]  
 [322.49316 334.06796 392.51852 461.62012 461.62012]]   

In [ ]:
with tf.Session(graph=graph) as sess:
    sess.run(tf.global_variables_initializer())
    filters = sess.run(W)
    
    conv_output = sess.run(conv_out)
    
    after_pooling = sess.run(conv_pool)

###sanity check
print(conv_out)
print(conv_pool)
print(conv_output[0,100:105,200:205, 7])
print("\n", after_pooling[0,100:105,200:205, 7])


with open("output.txt", "w+") as file:
    file.write("mean1 = %f" %np.mean(conv_output))
    file.write("\nmean2 = %f" %np.mean(after_pooling))

- Run the below cell to visualize the actual filters and plot the convolution output.       

In [ ]:
def show_conv_results(data, title):
    fig1 = plt.figure()
    fig1.suptitle(title, fontsize=30)
    rows, cols = 4, 8
    for i in range(np.shape(data)[3]):
        img = data[0, :, :, i]
        ax1 = fig1.add_subplot(rows, cols, i + 1)
        ax1.imshow(img, interpolation='none')
        ax1.axis('off')
        

def show_weights(W,title):
    fig2 = plt.figure()
    fig2.suptitle(title, fontsize=30)
    rows, cols = 4, 8
    for i in range(np.shape(W)[3]):
        img = W[:, :, 0, i]
        ax2 = fig2.add_subplot(rows, cols, i + 1)
        ax2.imshow(img, interpolation='none')
        ax2.axis('off')

show_weights(filters, title = "filters, "+"shape:" +str(filters.shape))
show_conv_results(conv_output, title = "after_convolution, "+ "shape:" + str(conv_output.shape))
show_conv_results(after_pooling, title = "after_pooling, "+"shape:"+str(after_pooling.shape))
        